export class Lang {
  static default_lang = "zh_cn";
  static langs = {
    zh_cn: {
      add: "添加",
      module_list: "模块列表",
      funcs_list: "功能项列表",
      tag: "标记",
      name: "名称",
      type: "类型",
      auth: "鉴权",
      operate: "操作",
      confirm: "确定",
      cancel: "取消",
      Read_write_type: "读写类型",
      none:"无",
      read:"只读",
      write:"只写",
      rw:"读写",
      check_auth_str:"访问时，是否需要验证权限",
      user1: "用户：",

      user2: "",
      user3: "",
      user4: "",
      user5: "",
      user6: "立即注册",
      user7: "用户名不能为空",
      user8: "密码不能为空",
      user9: "用户名不存在",
      user10: "密码不正确",
      user11: "该用户被禁用",
      user12: "登录失败",
      user13: "用户注册",
      user14: "仅支持字母、数字且首字符必须为字母",
      user15: "",
      user16: "长度6-16个字符且不能包含空格",
      user17: "确认密码",
      user18: "验证码",
      user19: "看不清，换一张",
      user20: "点击获取验证码",
      user21: "",
      user22: "用户名输入不合法",
      user23: "邮箱不能为空",
      user24: "邮箱格式不正确",
      user25: "密码长度不能小于6位",
      user26: "密码长度不能大于16位",
      user27: "密码不能包含空格",
      user28: "两次输入的密码必须相同",
      user29: "验证码不能为空",
      user30: "手机号码格式错误",
      user31: "验证码错误",
      user32: "用户名已存在",
      user33: "账号登录",
      user34: "设备登录",
      user35: "忘记密码？",
      user36: "没有账号？",
      user37: "手机号已被注册",
      user38: "",
      user39: "欢迎：",
      user40: "修改密码",
      user41: "账号",
      user42: "注册失败",
      edit: "编辑",
      remove: "删除",
      username: "用户名",
      password: "密码",

      nick: "昵称",
      login: "登 录",
      logout: "注销",
      mobile: "手机号",
      email: "邮箱",
      reg: "注册",
      day: "天",
      close1: "关闭",
      save: "保存",
      save1: "保存成功",
      save2: "保存失败",
      add1: "添加成功",
      add2: "添加失败",
      del1: "删除成功",
      del2: "删除失败",
      oper1: "操作成功",
      oper2: "操作失败",
      modify1: "修改成功",
      modify2: "修改失败",
      move1: "移动成功",
      move2: "移动失败",
      serverErr: "服务器错误",
      admin1: "服务器管理",
      admin2: "软件管理",
      admin3: "用户管理",
      admin4: "设备管理",
      admin5: "通道管理",
      admin6: "管理员账号",
      admin7: "当前管理员：",
      admin8: "状态",
      admin9: "所有",
      admin10: "正常",
      admin11: "禁用",
      admin12: "搜索",
      admin13: "添加",
      admin14: "角色管理",
      admin15: "添加管理员",
      admin16: "角色",
      admin17: "管理员账号",
      admin18: "手机号",
      admin19: "编辑管理员信息",
      admin20: "添加角色",
      admin21: "删除角色",
      admin22: "锁定/解锁管理员",
      admin23: "修改管理员权限",
      admin24: "根服务器配置",
      admin25: "添加服务器",
      admin26: "删除服务器",
      admin27: "服务器信息查看",
      admin28: "服务器信息修改",
      admin29: "pc端软件管理",
      admin30: "android端软件管理",
      admin31: "ios端软件管理",
      admin32: "查看用户信息",
      admin33: "添加用户",
      admin34: "修改用户信息",
      admin35: "锁定/解锁用户",
      admin36: "管理用户分组",
      admin37: "管理用户共享信息",
      admin38: "管理用户子账号",
      admin39: "数据读取中……",
      admin40: "注册时间",
      admin41: "上次登录",
      admin42: "操作",
      admin43: "启用",
      admin44: "无权限操作",
      admin45: "确认要锁定管理员：",
      admin46: "确认要解锁管理员：",
      admin47: "提示",
      admin48: "该管理员已被删除",
      admin49: "禁用失败",
      admin50: "启用失败",
      admin51: "加星号的选项不能为空",
      admin52: "编辑用户信息",
      admin53: "该管理员已存在",
      admin54: "账号太长",
      admin55: "请输入角色名",
      admin56: "确认要删除角色：",
      admin57: "单个添加",
      admin58: "批量添加",
      admin59: "用户级别",
      admin60: "免费用户",
      admin61: "到期时间",
      admin62: "修改分组名",
      admin63: "添加兄弟分组",
      admin64: "添加子分组",
      admin65: "分组上移",
      admin66: "分组下移",
      admin67: "删除分组",
      admin68: "别人共享给我",
      admin69: "允许别人共享给我",
      admin70: "我共享给别人",
      admin71: "分组管理",
      admin72: "共享管理",
      admin73: "子账号",
      admin74: "最新活跃时间",
      admin75: "确认要锁定用户：",
      admin76: "确认要解锁用户：",
      admin77: "该用户已被删除",
      admin78: "数字账号已用完",
      admin79: "该分组的父分组是共享分组，不能执行此操作",
      admin80: "拖动失败",
      admin81: "当前移动分组不存在",
      admin82: "目标分组是共享分组，不能执行此操作",
      admin83: "目标分组不存在",
      admin84: "请输入分组名",
      admin85: "未找到该分组",
      admin86: "是否确定删除分组：",
      admin87: "系统升级",
      admin88: "当前版本：",
      admin89: "升级包：",
      admin90: "升级包格式错误，请重新上传",
      //modbus
      admin91: "modbus设备管理",
      admin92: "添加设备",
      admin93: "修改设备",
      admin94: "删除设备",
      admin95: "设备id",
      admin96: "设备名",
      admin97: "协议",
      admin98: "详细",
      admin99: "确认要删除modbus设备：",
      admin100: "请不要输入特殊字符",
      admin101: "设备地图管理",
      admin102: "确认要删除modbus设备标注：",
      admin103: "该modbus设备不存在",
      admin104: "设置发电机状态类型",
      admin105: "保养时间",
      admin106: "运行时间",
      admin107: "自然时间",
      admin108: "短信发送",
      admin109: "消息推送",
      admin110: "日志",
      admin111: "设备日志",
      admin112: "用户日志",
      admin113: "请输入用户名：",
      admin114: "共享分组",
      admin115: "分组",
      admin116: "我的分组",

      admin_del_user: "删除用户",
      admin_del_mng: "删除管理员",

      //设备管理
      admin_devmng_sure_remove: "确证要删除设备: ",

      adminRole1: "管理员账号管理",
      adminRole2: "服务器管理",
      adminRole3: "软件升级管理",
      adminRole4: "用户管理",
      server1: "主平台服务器",
      server2: "地址",
      server3: "端口",
      server4: "webapi路径",
      server5: "mysql连接参数配置",
      server6: "主机",
      server7: "不安全的认证",
      server8: "已分配数字号段",
      server9: "运营商",
      server10: "服务器id",
      server11: "起始",
      server12: "结束",
      server13: "服务器群",
      server14: "新建服务器",
      server15: "服务器名称",
      server16: "客户端webapi地址",
      server17: "设备端webapi地址",
      server18: "摄像头封面图片路径",
      server19: "注册方式",
      server20: "字符账号",
      server21: "数字账号",
      server22: "注册验证方式",
      server23: "普通验证",
      server24: "短信验证",
      server25: "数字账号范围",
      server26: "图形验证码超时时间",
      server27: "短信验证码超时时间",
      server28: "设备心跳超时时间",
      server29: "秒",
      server30: "必须为纯数字",
      server31: "数字账号范围错误",
      server32: "数字账号范围重复",
      server33: "确认要禁用服务器：",
      server34: "确认要启用服务器：",
      server35: "确认要删除根服务器：",
      server36: "开发商",
      server37: "推送服务",
      server38: "报警上传最小间隔时间",
      server39: "确定要删除：",
      server40: "事件webapi地址",
      server41: "事件保存时间",
      server42: "天",
      server43: "（客户端接入用）",
      server44: "服务器",
      server45: "App key已存在",
      server46: "不能包含引号",
      server47: "鉴权服务器",
      server48: "主平台验证",
      server49: "服务器验证码",
      server50: "授权码",
      server51: "公钥",
      server52: "已上传",
      server53: "供应商",
      server54: "通道id",
      server55: "通道名",
      server56: "设备型号",
      server57: "最大通道数",
      server58: "固件版本",
      server59: "音频对讲方式",
      server60: "事件上报",
      server61: "无对讲",
      server62: "Onvif双工",
      server63: "私有双工",
      server64: "Onvif单工",
      server65: "私有单工",
      server66: "布防",
      server67: "撤防",
      server68: "码流数",
      server69: "服务器带宽",


      software1: "PC端软件",
      software2: "应用名",
      software3: "版本号",
      software4: "版本流水号",
      software5: "文件名",
      software6: "下载地址",
      software7: "上传文件",
      software8: "升级说明",
      software9: "Android端软件",
      software10: "上传二维码",
      software11: "IOS端软件",
      software12: "app store地址",
      software13: "图片文件格式错误，请重新上传",
      software14: "app store地址不能为空",
      software15: "设备端固件",

      forgetPass1: "发送重置密码邮件",
      forgetPass2: "发送",
      forgetPass3: "邮件发送成功，请注意查收。",
      forgetPass4: "该用户email未填写",
      forgetPass5: "email发送失败",
      regResult1: "恭喜您注册成功，",
      regResult2: "返回首页",
      resetPass1: "重置密码",
      resetPass2: "新密码",
      resetPass3: "确认新密码",
      resetPass4: "重置",
      plugin1: "点击这里下载控件",
      plugin2: "正在检查控件，请稍等",
      plugin3: "正在下载控件，请稍等",
      device1: "设备id",
      device2: "设备账号",
      device3: "设备密码",
      device4: "视频播放失败",
      device5: "获取摄像头列表失败",
      device6: "音频播放失败",
      device7: "连接",
      device8: "正在获取设备信息",
      device9: "正在搜索设备，请等待",
      device10: "设备列表已被更改，请重新操作",
      device11: "不能为空",
      device12: "操作失败",
      device13: "确定删除设备：",
      device14: "正在获取设备列表",
      device15: "添加设备",
      device16: "选择设备id",
      device17: "我的设备",
      device18: "我的摄像头",
      device19: "设备名：",
      device20: "型号：",
      device21: "当前没有设备，请添加",
      device22: "正在打开，请等待",
      device23: "设备密码错误",
      device24: "未验证",
      device25: "修改设备信息",
      device26: "设备端口号",
      device27: "设备网页端口号",
      device28: "设备名",
      device29: "该设备已存在",
      device30: "设备不在线",
      device31: "在线",
      device32: "离线",
      device33: "登陆超时，请检查TCP端口是否正确",
      device34: "帐号已登录",
      device35: "帐号已被锁定",
      device36: "帐号被列为黑名单",
      device37: "资源不足，系统忙",
      device38: "子连接失败",
      device39: "主连接失败",
      device40: "超过最大用户连接数",
      device41: "获取流水号失败",
      device42: "打开设备列表",
      device43: "开始时间",
      device44: "录像类型",
      device45: "普通",
      device46: "动检",
      device47: "报警",
      device48: "手动",
      device49: "请选择",
      device50: "请选择摄像头",
      device51: "获取设备信息失败",
      device52: "修改摄像头名称",
      device53: "摄像头id",
      device54: "摄像头名称",
      device55: "修改设备名称",
      device56: "时间",
      p2p_port_range1: "p2p端口范围不能为空",
      p2p_port_range2: "p2p端口范围的开始和结束之间的差不能小于100",
      p2p_port_range3: "p2p port range"
    },
    en: {
      add: 'add',
      module_list: 'Module List',
      funcs_list: 'Function List',
      tag: 'Tag',
      name: "Name",
      type: "Type",
      auth: "Auth",
      operate: "Operate",
      confirm: "Confirm",
      cancel: "Cancel",
      Read_write_type: "Read-write type",
      none:'None',
      read:"Read",
      write:'Write',
      rw:'Read Wite',
      check_auth_str:"Access, the need to verify permissions",


      user1: "user:",
      user2: "",
      user3: "",
      user4: "",
      user5: "",
      user6: "regist now",
      user7: "The username cannot be empty",
      user8: "The password cannot be empty",
      user9: "The account is not exists",
      user10: "The password is wrong",
      user11: "The username is disabled",
      user12: "Login failed",
      user13: "user register",
      user14: "Just support letters, numbers and the first character must be a letter",
      user15: "",
      user16: "Length should be 6-16 characters, and cannot contain blank space",
      user17: "Confirm password",
      user18: "Verification code",
      user19: "Not clear, change new one",
      user20: "Click here get verification code",
      user21: "",
      user22: "User name input not valid",
      user23: "Mailbox cannot be empty",
      user24: "The mailbox is not in the correct format",
      user25: "Password length cannot be less than 6",
      user26: "Password length cannot be greater than 16",
      user27: "Password cannot contain spaces",
      user28: "Input password twice must be the same",
      user29: "Verification code cannot be empty",
      user30: "Mobile phone number format error",
      user31: "Verification code error",
      user32: "The user name already exists",
      user33: "By account",
      user34: "By device id",
      user35: "forgot password?",
      user36: "no account?",
      user37: "",
      user38: "",
      user39: "Welcome：",
      user40: "Change password",
      user41: "Account",
      user42: "Failed to register",
      edit: 'edit',
      remove: 'remove',
      username: "Username",
      password: "Password",

      nick: "nickname",
      login: "Login",
      logout: "Logout",
      mobile: "Mobile Code",
      email: "Email",
      reg: "Regist",
      close1: "close",
      save: "save",
      save1: "Successfully saved",
      save2: "Save failed",
      add1: "Added successfully",
      add2: "Failed to add",
      del1: "Successfully deleted",
      del2: "Delete failed",
      oper1: "Successfully opertion",
      oper2: "Operation failed",
      modify1: "Modification successful",
      modify2: "Failed to modify",
      move1: "Move succeeded",
      move2: "Failed to move",
      admin1: "Server Management",
      admin2: "Software Management",
      admin3: "User Management",
      admin4: "Device Management",
      admin5: "Channel Management",
      admin6: "Manager Management",
      admin7: "Manager: ",
      admin8: "Status",
      admin9: "All",
      admin10: "Normal",
      admin11: "Disabled",
      admin12: "Search",
      admin13: "Add",
      admin14: "Manage Roles",
      admin15: "Add Manager Account",
      admin16: "Role",
      admin17: "Manager Account",
      admin18: "mobile",
      admin19: "Edit Informations of Manager",
      admin20: "Add Roles",
      admin21: "Remove Roles",
      admin22: "Enable/Disable Manager Account",
      admin23: "Change Rights of Manager",
      admin24: "Edit Root Server Informations",
      admin25: "Add Server",
      admin26: "Remove Server",
      admin27: "View Informations of Server",
      admin28: "Edit Informations of Server",
      admin29: "Manage PC Client Software",
      admin30: "Manage Android Client Software",
      admin31: "Manage IOS Client Software",
      admin32: "View Informations of User",
      admin33: "Add User",
      admin34: "Edit Informations of User",
      admin35: "Enable/Disable User",
      admin36: "Management of user groups",
      admin37: "Management of user information sharing",
      admin38: "User sub account management",
      admin39: "Data reading…",
      admin40: "Regist Time",
      admin41: "Last Login",
      admin42: "Functions",
      admin43: "Enable",
      admin44: "No permission to operate",
      admin45: "Confirm that you want to lock the administrator:",
      admin46: "Confirm that you want to unlock administrator:",
      admin47: "Hint",
      admin48: "The administrator has been deleted",
      admin49: "Disable failure",
      admin50: "Enable failed",
      admin51: "Asterisk options cannot be empty",
      admin52: "Edit user information",
      admin53: "The administrator has existed",
      admin54: "The account is too long",
      admin55: "Please enter a role name",
      admin56: "Are you sure you want to delete the role:",
      admin57: "Add",
      admin58: "Batch add",
      admin59: "The user level",
      admin60: "Free user",
      admin61: "Expiration time",
      admin62: "Modify group name",
      admin63: "Add brothers group",
      admin64: "Add subgroup",
      admin65: "Subgroup moved up",
      admin66: "Subgroup moved down",
      admin67: "Delete subgroup",
      admin68: "others share to me",
      admin69: "Allow others to share to me",
      admin70: "I shared with others",
      admin71: "Group management",
      admin72: "Sharing management",
      admin73: "Sub account",
      admin74: "Last Activie Time",
      admin75: "Confirm that you want to lock the user:",
      admin76: "Confirm that you want to unlock the user:",
      admin77: "This user has been deleted",
      admin78: "The digital ID has run out",
      admin79: "The parent group is shared group, this operation cannot be performed",
      admin80: "Failed to move",
      admin81: "The group does not exist",
      admin82: "The target group is sharing group, this operation cannot be performed",
      admin83: "The target group does not exist",
      admin84: "Please enter a group name",
      admin85: "The group has not found",
      admin86: "Are you sure you want to delete group:",
      admin87: "System upgrade",
      admin88: "The current version:",
      admin89: "Upgrade packs:",
      admin90: "Upgrade packs format error, please re upload",
      //设备管理
      admin_devmng_sure_remove: "Sure to remove device: ",
      admin_del_user: "Delete user",
      admin_del_mng: "Delete manager",
      adminRole1: "Rights of Manager Account Management",
      adminRole2: "Rights of Server Management",
      adminRole3: "Rights of Software Management",
      adminRole4: "Rights of User Management",
      server1: "Root Server",
      server2: "Server Address",
      server3: "Server Port",
      server4: "WebApi Path",
      server5: "Config MySQL",
      server6: "Host Address",
      server7: "InsecureAuth",
      server8: "Assigned digital ID section",
      server9: "Vendor",
      server10: "Server ID",
      server11: "Start",
      server12: "End",
      server13: "Server Group",
      server14: "New Server",
      server15: "Server Name",
      server16: "Client WebApi Url",
      server17: "Device WebApi Url",
      server18: "Snapshots Picture Folder",
      server19: "Sign-up method",
      server20: "Character user",
      server21: "Digital ID user",
      server22: "Registration authentication mode",
      server23: "Ordinary validate",
      server24: "Sms validate",
      server25: "Digital ID range",
      server26: "Captcha timeout",
      server27: "Sms authentication timeout",
      server28: "Device heartbeat timeout",
      server29: "S",
      server30: "Must be pure digital",
      server31: "Digital ID range error",
      server32: "Digital ID range repeated",
      server33: "Confirm to disable the server：",
      server34: "Confirm to enable the server：",
      server35: "Confirm to delete the server：",
      server36: "Vendor",
      server37: "Push service",
      server38: "Alarm upload minimum interval",
      server39: "确定要删除：",
      server40: "事件webapi地址",
      server41: "事件保存时间",
      server42: "days",
      server43: "（客户端接入用）",
      server44: "Server",
      server45: "App key已存在",
      server46: "不能包含引号",
      server47: "鉴权服务器",
      server48: "主平台验证",
      server49: "服务器验证码",
      server50: "授权码",
      server51: "公钥",
      server52: "已上传",
      server53: "供应商",
      server54: "Channel id",
      server55: "通道名",
      server56: "设备型号",
      server57: "Max channels",
      server58: "固件版本",
      server59: "音频对讲方式",
      server60: "事件上报",
      server61: "无对讲",
      server62: "Onvif双工",
      server63: "私有双工",
      server64: "Onvif单工",
      server65: "私有单工",
      software1: "PC Client",
      software2: "Application Name",
      software3: "Version",
      software4: "Version Code",
      software5: "Filename",
      software6: "Download Url",
      software7: "Upload",
      software8: "What’s New",
      software9: "Android Client",
      software10: "Upload QR Code",
      software11: "IOS Client",
      software12: "App Store Address",
      software13: "Image file format error, please re upload",
      software14: "App store address cannot be empty",
      software15: "Device firmware",

      forgetPass1: "Send the password reset e-mail",
      forgetPass2: "send",
      forgetPass3: "Email sent successfully, please check.",
      forgetPass4: "The user email is not filled",
      forgetPass5: "Email failed to send.",
      regResult1: "Congratulations on your successful registration,",
      regResult2: "Return to the home page",
      resetPass1: "reset password",
      resetPass2: "new password",
      resetPass3: "Confirm new password",
      resetPass4: "reset",
      plugin1: "click here to download the plugins.",
      plugin2: "checking the plugins, please waiting.",
      plugin3: "Downloading the plugin, please waiting.",
      device1: "Device id",
      device2: "Device username",
      device3: "Device password",
      device4: "Failed to play video",
      device5: "Get camera list failed",
      device6: "Failed to play audio",
      device7: "connect",
      device8: "getting device info",
      device9: "searching devices, please waiting.",
      device10: "The device list has been changed, Please operate again",
      device11: "cannot be empty",
      device12: "The operation failed",
      device13: "Confirm to delete device:",
      device14: "Getting device list",
      device15: "Add device",
      device16: "Select the device id",
      device17: "My devices",
      device18: "My cameras",
      device19: "name:",
      device20: "model:",
      device21: "There is no device, Please add",
      device22: "Opening, please wait",
      device23: "The device password error",
      device24: "Unchecked",
      device25: "Modify device information",
      device26: "Device port",
      device27: "Device web port",
      device28: "Device name",
      device29: "The deivce already exists",
      device30: "The Device is not online",
      device31: "Online",
      device32: "Offline",
      device33: "Login timeout, Please check the TCP port is correct",
      device34: "Account is logged",
      device35: "Account is locked",
      device36: "The account was deined",
      device37: "System is busy",
      device38: "Sub connection failed",
      device39: "Main connection failed",
      device40: "Out of the maximum connections",
      device41: "Failed to get the sn",
      device42: "Open device page",
      device43: "Start time",
      device44: "Video type",
      device45: "Ordinary",
      device46: "Dynamic",
      device47: "Alarm",
      device48: "Manual",
      device49: "Please select",
      device50: "Please select a camera",
      device51: "Failed to get equipment information",
      device52: "Modify the name of camera",
      device53: "Camera id",
      device54: "Camera name",
      device55: "Modify the name of device",
      device56: "time",
      p2p_port_range1: "p2p port range cannot be empty",
      p2p_port_range2: "p2p port keeping always at least 100 ports of difference between start and end range",
      p2p_port_range3: "p2p port range"
    }
  }
}
